from __future__ import annotations

COMPANY_SLUGS = {
    "Google": "google",
    "Microsoft": "microsoft",
    "Amazon": "amazon",
    "Meta": "meta",
    "Apple": "apple",
    "Netflix": "netflix",
    "NVIDIA": "nvidia",
    "Adobe": "adobe",
    "Salesforce": "salesforce",
    "Stripe": "stripe",
    "Uber": "uber",
    "Atlassian": "atlassian",
    "Databricks": "databricks",
    "Snowflake": "snowflake",
    "Oracle": "oracle",
    "Cisco": "cisco",
    "Intel": "intel",
    "AMD": "amd",
    "Qualcomm": "qualcomm",
    "Samsung": "samsung",
    "Spotify": "spotify",
    "Cloudflare": "cloudflare",
    "MongoDB": "mongodb",
    "GitLab": "gitlab",
    "GitHub": "github",
    "OpenAI": "openai",
    "Anthropic": "anthropic",
    "Perplexity": "perplexity",
    "TikTok": "tiktok",
    "ByteDance": "bytedance",
    "Rivian": "rivian",
    "Tesla": "tesla",
    "Airbnb": "airbnb",
    "Dropbox": "dropbox",
    "Pinterest": "pinterest",
    "Reddit": "reddit",
    "Discord": "discord",
    "Canva": "canva",
    "Twilio": "twilio",
    "PayPal": "paypal",
    "Shopify": "shopify",
    "IBM": "ibm",
}
