name: Docs Deployment Tracker
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 * * *" # scheduling so it automatically fetches, without manual trigger

permissions:
  contents: read
  deployments: write

concurrency:
  group: docs-deployment
  cancel-in-progress: true

jobs:
  record:
    runs-on: ubuntu-latest
    steps:
      - run: echo "Tracking Mintlify docs deployment"
    environment:
      name: staging - docs
      url: https://careers-engine.zenyukti.in
